### ISSUE TITLE
Weirdness after recent changes

### ISSUE THREAD

**Issue by tpaschalis** [grafana/tns#21]
So I tried to follow through the README and had some issues with the current status of `main`; on the other hand, the following points work fine in 133a635 (last changes early November).

As it's my first time watching how everything pieces together, I haven't found the cause so I'm initially reaching out for visibility.

So currently:
- No data is being presented in the "TNS/Demo App" dashboard
- The Prometheus query in the README, no longer work as-is; the metric name has changed a bit, and the 1m resolution returns an empty dataset
```
-- Run this query `histogram_quantile(.99, sum(rate(tns_request_duration_seconds_bucket{}[1m])) by (le))`
+- Run this query `histogram_quantile(.99, sum(rate(tns_client_request_duration_seconds_bucket[5m])) by (le))`
```

- The Loki query in the README, no longer work as-is; while `level` exists as a label the current query returns 0 results, _but_ it works if passed after the logfmt filter

```
-- Run this query `{job="tns/app", level="info"} | logfmt | status>=500 and status <=599 and duration > 50ms`
+- Run this query `{job="tns/app"} | logfmt | level="info" | status>=500 and status <=599 and duration > 50ms`
```

**Comment by 56quarters** [comment]
The problem with the dashboard at least is the issue you've already identified: all the dashboards are using 1m resolution but scrapes are now happening at a 1m interval (instead of the previous 15s) to align with how Grafana Cloud pricing works. I can open a PR to fix that at least.

**Comment by 09jvilla** [comment]
It looks like the other issues @tpaschalis pointed out can be solved with an update to the readme. 
Happy to make a PR for this, but @56quarters would just want to get your thumbs up that these differences that @tpaschalis observed are expected given the changes you made.

**Comment by 56quarters** [comment]
> It looks like the other issues @tpaschalis pointed out can be solved with an update to the readme. Happy to make a PR for this, but @56quarters would just want to get your thumbs up that these differences that @tpaschalis observed are expected given the changes you made.

Yeah, I'm trying to understand the Loki/label issue why that would have changed.

**Comment by 56quarters** [comment]
> > It looks like the other issues @tpaschalis pointed out can be solved with an update to the readme. Happy to make a PR for this, but @56quarters would just want to get your thumbs up that these differences that @tpaschalis observed are expected given the changes you made.
> 
> Yeah, I'm trying to understand the Loki/label issue why that would have changed.

Oh, actually it's just because the new config drops the pipeline stages that were parsing it before. I don't want to add back regex pipeline stages if we can just get away with using `logfmt`. I'll update the README

**Comment by 56quarters** [comment]
@tpaschalis Can you give the latest `main` another try? I believe the issues should be fixed. Thanks!

**Comment by tpaschalis** [comment]
That was fast! 😅  

Yes, the example works great now, I can see data in the dashboard, the exemplars are there, and the queries return data normally! Thanks you both folks!

**Comment by 09jvilla** [comment]
Thank you for helping us test it out :)
