### ISSUE TITLE
DB and App traces are not connected

### ISSUE THREAD

**Issue by aocenas** [grafana/tns#4]
When running the app with Jaeger tracing enabled both DB and App traces are logged but as totally separate traces with different traceIDs not as 2 spans of the same trace. Looking at the code it seems like the handling to extract traceID from the request is there so could be some misconfiguration.

**Comment by gouthamve** [comment]
Could you share a screenshot?

**Comment by aocenas** [comment]
<img width="1238" alt="Screenshot 2019-10-11 at 12 39 29" src="https://user-images.githubusercontent.com/1014802/66645620-3db8a680-ec24-11e9-87bb-1f132e50035b.png">
<img width="1238" alt="Screenshot 2019-10-11 at 12 39 39" src="https://user-images.githubusercontent.com/1014802/66645621-3db8a680-ec24-11e9-87ba-f5b52eaab509.png">

@gouthamve does this help?

Those 2 should be one request so I would assume at least for the App service trace, that it would contain also spans for DB service.

**Comment by aocenas** [comment]
also the configuration I am using is in https://github.com/grafana/tns/pull/2 as I used docker-compose to run it with Jeager running in https://github.com/grafana/grafana/tree/master/devenv

**Comment by tomwilkie** [comment]
Fixed in 1144b925e2f886c85ba5664330eaea2c0cccf5f5
